export JAX_COMPILATION_CACHE_DIR="/dev/shm/jax_cache" && \
export JAX_PERSISTENT_CACHE_MIN_ENTRY_SIZE_BYTES=-1 && \
export JAX_PERSISTENT_CACHE_MIN_COMPILE_TIME_SECS=0 && \
export HF_HUB_CACHE=/dev/shm/hf_cache && \
export XLA_PYTHON_CLIENT_MEM_FRACTION=0.95 && \
export JAX_DEFAULT_MATMUL_PRECISION=bfloat16 && \
export LIBTPU_INIT_ARGS='--xla_tpu_dvfs_p_state=7 \
--xla_tpu_spmd_rng_bit_generator_unsafe=true \
--xla_tpu_enable_dot_strength_reduction=true \
--xla_tpu_enable_async_collective_fusion_fuse_all_gather=true \
--xla_enable_async_collective_permute=true \
--xla_tpu_enable_data_parallel_all_reduce_opt=true \
--xla_tpu_data_parallel_opt_different_sized_ops=true \
--xla_tpu_enable_async_collective_fusion=true \
--xla_tpu_enable_async_collective_fusion_multiple_steps=true \
--xla_tpu_overlap_compute_collective_tc=true \
--xla_enable_async_all_gather=true \
--xla_tpu_scoped_vmem_limit_kib=81920 \
--xla_tpu_enable_async_all_to_all=true \
--xla_tpu_enable_all_experimental_scheduler_features=true \
--xla_tpu_enable_scheduler_memory_pressure_tracking=true \
--xla_tpu_host_transfer_overlap_limit=24 \
--xla_tpu_aggressive_opt_barrier_removal=ENABLED \
--xla_lhs_prioritize_async_depth_over_stall=ENABLED \
--xla_should_allow_loop_variant_parameter_in_chain=ENABLED \
--xla_should_add_loop_invariant_op_in_chain=ENABLED \
--xla_max_concurrent_host_send_recv=100 \
--xla_tpu_scheduler_percent_shared_memory_limit=100 \
--xla_latency_hiding_scheduler_rerun=2 \
--xla_tpu_use_minor_sharding_for_major_trivial_input=true \
--xla_tpu_relayout_group_size_threshold_for_reduce_scatter=1 \
--xla_tpu_strict_fp32_to_bf16_conversion=false \
--xla_tpu_use_enhanced_fp32_for_bf16_conversions=true \
--xla_tpu_enable_latency_hiding_scheduler=true \
--xla_tpu_all_reduce_combine_threshold_bytes=1073741824 \
--xla_tpu_all_gather_combine_threshold_bytes=1073741824 \
--xla_tpu_reduce_scatter_combine_threshold_bytes=1073741824 \
--xla_tpu_enable_fast_collective_permute=true \
--xla_tpu_latency_hiding_scheduler_rerun_with_more_overlap_opportunities=true \
--xla_tpu_vectorize_all_reduce_scatter=true \
--xla_tpu_dot_dimension_layout_optimization=true \
--xla_tpu_memory_bound_loop_optimizer_options=all \
--xla_tpu_enable_megacore_fusion=true \
--xla_tpu_assign_all_reduce_scatter_layout=true' && \
export HF_HUB_CACHE=/dev/shm/maxdiffusion_hf_cache/ && \
export HF_HUB_ENABLE_HF_TRANSFER=1 && \
HF_HUB_CACHE=/dev/shm python wan2p2_t2v_benchmark_magcache.py --size 720*1280 --sample_steps 40 --batch_size 1 --dp 2 --bq 4864 --bkv 1024 --bkv_compute 1024 --bkv_compute_in 1024 --frame_num 81
